import dotenv from "dotenv";
dotenv.config();
export default {
  extra: {
    EXPO_PUBLIC_APIKEY: process.env.EXPO_PUBLIC_APIKEY,
    EXPO_PUBLIC_AUTHDOMAIN: process.env.EXPO_PUBLIC_AUTHDOMAIN,
    EXPO_PUBLIC_PROJECTID: process.env.EXPO_PUBLIC_PROJECTID,
    EXPO_PUBLIC_STORAGEBUCKET: process.env.EXPO_PUBLIC_STORAGEBUCKET,
    EXPO_PUBLIC_MESSAGINGSENDERID: process.env.EXPO_PUBLIC_MESSAGINGSENDERID,
    EXPO_PUBLIC_APPID: process.env.EXPO_PUBLIC_APPID,
    EXPO_PUBLIC_MEASUREMENTID: process.env.EXPO_PUBLIC_MEASUREMENTID,
  },
};
